package edu.estu.recipeapp.entity;

public enum Unit {
    BOTTLE, CAN, CUP, DASH, DROP, GALLON, GRAM, KILOGRAM, LITER, MILLILITER, OUNCE, PINT, POUND, QUART, TABLESPOON, TEASPOON, COUNT, PIECE, SLICE, HANDFUL
}